package ir.vasl.chatkitv4core.model.chatkitv4enums

enum class MediaHelperStatus {

    IDLE,
    SUBMITTED,
    ERROR,
    TERMINATE,

    DOWNLOAD_PREPARING,
    DOWNLOAD_STARTED,
    DOWNLOAD_STOPPED,
    DOWNLOAD_FAILED,
    DOWNLOAD_IN_PROGRESS,
    DOWNLOAD_SUCCESS,

    PLAYER_PREPARING,
    PLAYER_PREPARED,
    PLAYER_PAUSED,
    PLAYER_RESUMED,
    PLAYER_STOPPED,
    PLAYER_ERROR,
    PLAYER_STARTED,
    PLAYER_PLAYING,
    PLAYER_PROGRESS,
    PLAYER_COMPLETED,

}