package ir.vasl.chatkitv4core.model.chatkitv4enums

enum class MessageConditionStatus(key: String, value: Int) {

    // global
    IDLE("IDLE", -2),
    UNDEFINED("UNDEFINED", -1),

    // uploader
    UPLOAD_IN_PROGRESS("UPLOAD_IN_PROGRESS", 0),
    UPLOAD_FAILED("UPLOAD_FAILED", 1),
    UPLOAD_SUCCEED("UPLOAD_SUCCEED", 2),
    UPLOAD_STOPPED("UPLOAD_STOPPED", 3),

    // downloader
    DOWNLOAD_STARTED("DOWNLOAD_STARTED", 4),
    DOWNLOAD_IN_PROGRESS("DOWNLOAD_IN_PROGRESS", 5),
    DOWNLOAD_FAILED("DOWNLOAD_FAILED", 6),
    DOWNLOAD_SUCCEED("DOWNLOAD_SUCCEED", 7),
    DOWNLOAD_STOPPED("DOWNLOAD_STOPPED", 8),
    DOWNLOAD_NEEDED("DOWNLOAD_NEEDED", 9),

    // player
    PLAYER_STARTED("PLAYER_STARTED", 10),
    PLAYER_IN_PROGRESS("PLAYER_IN_PROGRESS", 11),
    PLAYER_PAUSED("PLAYER_PAUSED", 12),
    PLAYER_STOPPED("PLAYER_STOPPED", 13),
    PLAYER_FAILED("PLAYER_FAILED", 14),
    PLAYER_FINISHED("PLAYER_FINISHED", 15),

}